apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simon-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: www.sbriggshackathon.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simon-service
            port:
              number: 80
