apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deploy
  namespace: simonhackathon
spec:
  serviceName: s1
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
      - name: dockerhubsecret1
      containers:
        - name: c1
          image: docker.io/sbriggs80/hackathon:hackathondbv1.0
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123"
          volumeMounts:
            - name: simondb
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: simondb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-csi
        resources:
          requests:
            storage: 20G
